### ISSUE TITLE
Error while building the SDG of a class

### ISSUE THREAD

**Issue by DogaKilic** [joana-team/joana#13]
I get an error when i try to build the SDG of a class, like this: 

`java.lang.ArrayIndexOutOfBoundsException: -1
	at com.ibm.wala.ssa.SSAInvokeInstruction.substitudeUses(Unknown Source)
	at com.ibm.wala.ssa.analysis.TrivialPhiElimination.updateTrivialPhiReferences(Unknown Source)
	at com.ibm.wala.ssa.analysis.TrivialPhiElimination.perform(Unknown Source)
	at com.ibm.wala.classLoader.ShrikeIRFactory$1.eliminateTrivialPhis(Unknown Source)
	at com.ibm.wala.classLoader.ShrikeIRFactory$1.<init>(Unknown Source)
	at com.ibm.wala.classLoader.ShrikeIRFactory.makeIR(Unknown Source)
	at com.ibm.wala.ssa.DefaultIRFactory.makeIR(Unknown Source)
	at com.ibm.wala.ssa.SSACache.findOrCreateIR(Unknown Source)
	at com.ibm.wala.ipa.callgraph.AnalysisCache.getIR(Unknown Source)
	at com.ibm.wala.ipa.callgraph.propagation.cfa.ContextInsensitiveSSAInterpreter.getIR(Unknown Source)
	at com.ibm.wala.ipa.callgraph.propagation.cfa.DefaultSSAInterpreter.getIR(Unknown Source)
	at com.ibm.wala.ipa.callgraph.propagation.cfa.FallbackContextInterpreter.getIR(Unknown Source)
	at com.ibm.wala.ipa.callgraph.propagation.cfa.DelegatingSSAContextInterpreter.getIR(Unknown Source)
	at com.ibm.wala.ipa.callgraph.propagation.cfa.DelegatingSSAContextInterpreter.getIR(Unknown Source)
	at com.ibm.wala.ipa.callgraph.impl.ExplicitCallGraph$ExplicitNode.getIR(Unknown Source)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.getTargetPointerKey(Unknown Source)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.processCallingConstraints(Unknown Source)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.processResolvedCall(Unknown Source)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.access$200(Unknown Source)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$ConstraintVisitor.visitInvokeInternal(Unknown Source)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$ConstraintVisitor.visitInvoke(Unknown Source)
	at com.ibm.wala.ssa.SSAInvokeInstruction.visit(Unknown Source)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addBlockInstructionConstraints(Unknown Source)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addNodeInstructionConstraints(Unknown Source)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.unconditionallyAddConstraintsFromNode(Unknown Source)
	at com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder.addConstraintsFromNode(Unknown Source)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.addConstraintsFromNewNodes(Unknown Source)
	at com.ibm.wala.ipa.callgraph.propagation.StandardSolver.solveImpl(Unknown Source)
	at com.ibm.wala.ipa.callgraph.propagation.StandardSolver.solve(Unknown Source)
	at com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.makeCallGraph(Unknown Source)
	at edu.kit.joana.wala.core.SDGBuilder.buildCallgraph(Unknown Source)
	at edu.kit.joana.wala.core.SDGBuilder.run(Unknown Source)
	at edu.kit.joana.wala.core.SDGBuilder.buildAndKeepBuildArtifacts(Unknown Source)
	at edu.kit.joana.api.sdg.SDGBuildPreparation.computeAndKeepBuildArtifacts(Unknown Source)
	at edu.kit.joana.api.sdg.SDGProgram.createSDGProgram(Unknown Source)
	at edu.kit.joana.api.sdg.SDGProgram.createSDGProgram(Unknown Source)
	at edu.kit.joana.ui.ifc.wala.console.console.IFCConsole.createSDG(Unknown Source)
	at edu.kit.joana.ui.ifc.wala.console.console.IFCConsole.createSDG(Unknown Source)
	at edu.kit.joana.ui.ifc.wala.console.console.IFCConsole.buildSDG(Unknown Source)
	at edu.kit.joana.ui.ifc.wala.console.console.IFCConsole.access$1600(Unknown Source)
	at edu.kit.joana.ui.ifc.wala.console.console.IFCConsole$24.execute(Unknown Source)
	at edu.kit.joana.ui.ifc.wala.console.console.IFCConsole$CommandRepository.executeCommand(Unknown Source)
	at edu.kit.joana.ui.ifc.wala.console.console.IFCConsole.executeAndLogCommand(Unknown Source)
	at edu.kit.joana.ui.ifc.wala.console.console.IFCConsole.processCommand(Unknown Source)
	at edu.kit.joana.ui.ifc.wala.console.gui.IFCConsoleGUI$2.run(Unknown Source)
`

I'm using the basic graphical UI version of JOANA found in [https://pp.ipd.kit.edu/projects/joana/](url).

While building the SDG, I use the default settings of JOANA.

The class that prodcues the error can be found in [ScratchSwitch.zip](https://github.com/joana-team/joana/files/7693037/ScratchSwitch.zip).

The class that produces the error is ScratchSwitchProcessed.
I get ScratchSwitchProcessed by preprocessing ScratchSwitch, which produces no errors on SDG build.

**Comment by ratefuchs** [comment]
The given example is incomplete (both the Connection and util.Row are missing; and there are no *.java files).
Also, in the current state it doesn't seem like it is a minimal example (it contains several StringBuilder operations, String constants, multiple switch branches, Exception handling of an exception that cannot even be thrown, ...; they are very likely not relevant to the bug).
For us to reproduce the bug we need a minimal example, i.e. the example has to
1. be complete and include *.java and *.class files of all of your classes
2. be minimal, so it should exhibit the bug, but by removing any part of the example the bug is not triggered anymore.
